server:
  port: 2021

spring:
  application:
    name: cart-service
  jpa:
    # Auto tables generation
    generate-ddl: false
    # db migration option
    hibernate:
      ddl-auto: validate
  # datasource url
  datasource:
    url: jdbc:mysql://localhost:3306/cartdb
    username: "root"
    password: "0000"

feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"

com:
  aspire:
    exceptions:
      NoHandlerFoundForCommandException:
        code: "0001"
        messages:
          EN: No Command Handler Found
          AR: لايوجد من يقوم بتلبية الطلب
      NoHandlerFoundForQueryException:
        code: "0002"
        messages:
          EN: No Query Handler Found
          AR: لايوجد من يقوم بتلبية الطلب
